name: Deploy messanger server
on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    deploy:
        env:
            CI: ""
        runs-on: ubuntu-latest
        steps:
            -  name: Checkout
               uses: actions/checkout@v2.3.1
               with:
                   persistent-credentials: false

            - name: Install and test
              env:
                  MONGO_URL: ${{secrets.MONGO_URL}}
              run: |
                  npm install
#                  npm run ci

            - name: Build image
              run: docker build -t messanger/server .

            - name: Deploy image 🚀
              uses: jwalton/gh-ecr-push@v1
              with:
                  access-key-id: ${{ secrets.AWS_ACCESS }}
                  secret-access-key: ${{ secrets.AWS_SECRET }}
                  region: eu-central-1
                  local-image: messanger/server
                  image: messanger/server:${{github.sha}}
