on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    deploy:
        env:
            CI: ""
        runs-on: ubuntu-latest
        steps:
            -  name: Checkout
               uses: actions/checkout@v2.3.1
               with:
                   persistent-credentials: false

            - name: Install and test
              run: |
                  npm install
                  npm run ci

            - name: Build
              run: |
                  npm run build

            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.6.8
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: messangerkx
                  heroku_email: cssuperpy@gmail.com
