name: Deploy messanger server
on:
    push:
        branches:
            - master

    pull_request:
        branches:
            - master

jobs:
    deploy:
        env:
            CI: ""
        runs-on: ubuntu-latest
        steps:
            -  name: Checkout
               uses: actions/checkout@v2.3.1
               with:
                   persistent-credentials: false

            - name: Build image
              run: docker build -t messanger/server:prod.${{github.sha}} .

            - name: Push to ecr
              uses: jwalton/gh-ecr-push@v1
              with:
                  access-key-id: ${{ secrets.AWS_ACCESS }}
                  secret-access-key: ${{ secrets.AWS_SECRET }}
                  region: eu-central-1
                  local-image: messanger/server:prod.${{github.sha}}
                  is-semver: true
                  image: messanger/server

            - name: Deploy new app
              uses: chrislennon/action-aws-cli@v1.1
              # All commands after this point have access to the AWS CLI
            - run: aws elasticbeanstalk restart-app-server --environment-name Messanger-env
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
